version: "3"
services:
  db:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dash
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  h2:
    image: oscarfonts/h2:latest
    container_name: h2
    ports:
      - "8082:8082"
      - "1521:1521"
    environment:
      H2_OPTIONS: '-tcpAllowOthers -tcpPort 1521 -web -webAllowOthers -webPort 8082'

volumes:
  postgresql:
  postgresql_data: