apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: <IMAGE_PLACEHOLDER>
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://bd-pixel.postgres.database.azure.com:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: pixel
        - name: SPRING_DATASOURCE_PASSWORD
          value: NeymarJr2024
        - name: DATABASE_NAME    
          value: postgres   
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi