name: Deploy to AKS Cluster
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: Azure/docker-login@v1
      with:
        login-server: springapppixel.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build . -t springapppixel.azurecr.io/backend:${{ github.sha }}
        docker push springapppixel.azurecr.io/backend:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: pixelCluster
        resource-group: gr-pixel-containers
        
    - uses: Azure/k8s-create-secret@v1
      with:
        container-registry-url: springapppixel.azurecr.io
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}
        secret-name: k8s-secret

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          springapppixel.azurecr.io/backend:${{ github.sha }}
        imagepullsecrets: |
          k8s-secret